### ISSUE TITLE
Timeout Issues

### ISSUE THREAD

**Issue by KyanHexagon** [Tw1sm/spraycharles#23]
Periodically I'll come across a target where spraycharles will consistently crash with a timeout error and even setting the timeout to something crazy high like 3600 doesn't seem to make a difference. I generally use spraycharles for spraying against NTLM logins and this is where I have experienced this the most.

Here is an example of the error that is shown when it crashes (although this is from spraying against smb, which I know timeout has no effect on):

```
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/nmb.py", line 902, in _setup_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/spraycharles", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/spraycharles/spraycharles.py", line 716, in spray
    spraycharles.spray()
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/spraycharles/spraycharles.py", line 454, in spray
    self._login(username, password)
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/spraycharles/spraycharles.py", line 377, in _login
    response = self.target.login(username, password)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/spraycharles/targets/Smb.py", line 70, in login
    self.conn = SMBConnection(self.host, self.host, None, 445)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/smbconnection.py", line 80, in __init__
    self.negotiateSession(preferredDialect)
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/smbconnection.py", line 120, in negotiateSession
    packet = self.negotiateSessionWildcard(self._myName, self._remoteName, self._remoteHost, self._sess_port,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/smbconnection.py", line 169, in negotiateSessionWildcard
    self._nmbSession = nmb.NetBIOSTCPSession(myName, remoteName, remoteHost, nmb.TYPE_SERVER, sess_port,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/nmb.py", line 893, in __init__
    NetBIOSSession.__init__(self, myname, remote_name, remote_host, remote_type=remote_type, sess_port=sess_port,
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/nmb.py", line 753, in __init__
    self._sock = self._setup_connection((remote_host, sess_port), timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/spraycharles/lib/python3.11/site-packages/impacket/nmb.py", line 905, in _setup_connection
    raise socket.error("Connection error (%s:%s)" % (peer[0], peer[1]), e)
OSError: [Errno Connection error (target:445)] timed out
```

Thanks in advance for any help you may offer. I think spraycharles is great and really appreciate the work that has gone into making it such a good tool.

**Comment by Tw1sm** [comment]
Thanks for the report. I'll take a look at this sometime. Entire spray logic/loop should likely be rewritten

**Comment by Tw1sm** [comment]
This specific SMB connection error gets handled now in 1e58d358dac699d8fbce5a75a62432a6289a306d. If encountered, spraycharles will wait 5 seconds and retry (until success) like the HTTP modules do.

Separately, I'm also working on a 2.0 release that will improve a lot of the code base and ideally include better overall error handling.

**Comment by Tw1sm** [comment]
Additional handling for any generic exception from the requests library added in e86cbc9

**Comment by Tw1sm** [comment]
Closing, feel free to reopen if the problem persists in the future
